-- begin CONTRACTCREATOR_CONTRACT
alter table CONTRACTCREATOR_CONTRACT add constraint FK_CONTRACTCREATOR_CONTRACT_ON_CUSTOMER foreign key (CUSTOMER_ID) references CONTRACTCREATOR_CUSTOMER(ID)^
alter table CONTRACTCREATOR_CONTRACT add constraint FK_CONTRACTCREATOR_CONTRACT_ON_PROVIDER foreign key (PROVIDER_ID) references CONTRACTCREATOR_PROVIDER(ID)^
create index IDX_CONTRACTCREATOR_CONTRACT_ON_CUSTOMER on CONTRACTCREATOR_CONTRACT (CUSTOMER_ID)^
create index IDX_CONTRACTCREATOR_CONTRACT_ON_PROVIDER on CONTRACTCREATOR_CONTRACT (PROVIDER_ID)^
-- end CONTRACTCREATOR_CONTRACT
-- begin CONTRACTCREATOR_PROVIDER
create unique index IDX_CONTRACTCREATOR_PROVIDER_UNIQ_INN on CONTRACTCREATOR_PROVIDER (INN) ^
create unique index IDX_CONTRACTCREATOR_PROVIDER_UNIQ_EMAIL on CONTRACTCREATOR_PROVIDER (EMAIL) ^
create unique index IDX_CONTRACTCREATOR_PROVIDER_UNIQ_PHONE on CONTRACTCREATOR_PROVIDER (PHONE) ^
-- end CONTRACTCREATOR_PROVIDER
-- begin CONTRACTCREATOR_CUSTOMER
create unique index IDX_CONTRACTCREATOR_CUSTOMER_UNIQ_PHONE on CONTRACTCREATOR_CUSTOMER (PHONE) ^
create unique index IDX_CONTRACTCREATOR_CUSTOMER_UNIQ_EMAIL on CONTRACTCREATOR_CUSTOMER (EMAIL) ^
-- end CONTRACTCREATOR_CUSTOMER
